import {StyleSheet} from 'react-native';
const style = StyleSheet.create({
  hero: {
    fontSize: 26.16,
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 18.01,
    marginTop: 12,
  },
  heroHolder: {
    paddingTop: 19,
    marginBottom: 48,
  },
  heading: {
    fontSize: 14.5,
    textAlign: 'center',
    fontWeight: 'regular',
    marginBottom: 3,
  },
  formView: {
    width: 380,
    backgroundColor: '#E6F5FF',
    // backgroundColor: 'red',
    borderRadius: 18,
    margin: 'auto',
  },
  pageType: {
    display: 'flex',
    flexDirection: 'row',
    marginBottom: 17,
    backgroundColor: 'white',
  },
  Login_register: {
    height: 48,
    width: 190,
    display: 'flex',
    justifyContent: 'center',
    borderTopLeftRadius: 8.72,
    borderTopRightRadius: 8.72,
  },
  Login_register_text: {
    fontSize: 19.19,
    fontWeight: 'medium',
    textAlign: 'center',
  },
  OtherLoginButton: {
    height: 57,
    width: 340,
    margin: 'auto',
    backgroundColor: '#FFFFFF',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 8,
    gap: 29.42,
  },
  OtherLoginButton_text: {
    fontSize: 19.19,
    fontWeight: 'medium',
  },
  logo: {
    height: 29.46,
    width: 28.58,
  },
  alt: {
    fontSize: 12,
    fontWeight: 'regular',
    backgroundColor: '#E6F5FF',
    position: 'absolute',
    top: -13.5,
    textAlign: 'center',
    left: '32.8%',
    padding: 4,
  },
  stroke: {
    borderBottomWidth: 1,
    width: 340,
    margin: 'auto',
    marginTop: 37,
    borderColor: '#CFDDE6',
    position: 'relative',
    marginBottom: 10,
  },
  EmailLogin: {
    width: 340,
    margin: 'auto',
    marginTop: 25,
  },

  inputSection: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    height: 55,
    paddingLeft: 17,
    borderRadius: 8,
    width: 340,
    margin: 'auto',
  },
  input: {
    width: '85%',
    backgroundColor: 'white',
    height: 54,
    borderRadius: 8,
    padding: 15,
  },
  ActionButtonHolder: {
    width: 340,
    margin: 'auto',
    marginTop: 33,
    marginBottom: 34,
  },
  login_signup_btn: {
    backgroundColor: '#0098FF',
    height: 58,
    textAlign: 'center',
    width: '100%',
    textAlignVertical: 'center',
    borderRadius: 10,
    fontSize: 23,
    fontWeight: 'bold',
    color: 'white',
  },
});
export default style;
